name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies and build
        run: |
          cd /var/www/html/pocketguru
          composer install --no-dev --prefer-dist --no-interaction --quiet
          npm install
          npm run production

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_SERVER }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          source: "." # Path to your Laravel project
          target: "/var/www/html/pocketguru" # Destination directory on the server

      - name: SSH into DigitalOcean server and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_SERVER }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          script: |
            cd /var/www/html/pocketguru # Change to your project's directory
            cp .env.example .env # Copy the example environment file
            php artisan key:generate # Generate application key
            php artisan migrate:fresh --force # Run database migrations
            php artisan config:cache # Cache configuration
            php artisan route:cache # Cache routes

      - name: Restart web server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_SERVER }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script: |
            sudo systemctl restart apache2 # Restart Apache or use the appropriate command for your web server
